services:
  - type: web
    name: shopflix-ai
    runtime: docker
    repo: https://github.com/mobilecasez/fix-merchant-app
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: SHOPIFY_API_KEY
        value: 2d4dfddeb80f9318dfb43e30a9175bc6
      - key: SHOPIFY_API_SECRET
        sync: false
      - key: SCOPES
        value: read_products,write_products,read_locations
      - key: DATABASE_URL
        value: file:./prisma/prod.db
      - key: HOST
        fromService:
          type: web
          name: shopflix-ai
          property: host
      - key: SHOPIFY_APP_URL
        fromService:
          type: web
          name: shopflix-ai
          property: host
