# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "adbe221d4ee5000b41a21b0117444917"
name = "ShopFlix AI"
application_url = "https://shopflixai-production.up.railway.app"
embedded = true

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "customers/data_request" ]
  uri = "/webhooks/customers/data_request"

  [[webhooks.subscriptions]]
  topics = [ "customers/redact" ]
  uri = "/webhooks/customers/redact"

  [[webhooks.subscriptions]]
  topics = [ "shop/redact" ]
  uri = "/webhooks/shop/redact"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_script_tags,write_script_tags"

[auth]
redirect_urls = [
  "https://shopflixai-production.up.railway.app/auth/callback",
  "https://shopflixai-production.up.railway.app/auth/shopify/callback",
  "https://shopflixai-production.up.railway.app/api/auth/callback"
]

[pos]
embedded = false
