# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "85d12decc346b5ec3cdfebacdce7f290"
name = "ShopFlix AI"
application_url = "https://fix-merchant-center-production.up.railway.app"
embedded = true

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_locations,read_products,write_products"

[auth]
redirect_urls = [
  "https://fix-merchant-center-production.up.railway.app/auth/callback",
  "https://fix-merchant-center-production.up.railway.app/auth/shopify/callback",
  "https://fix-merchant-center-production.up.railway.app/api/auth/callback"
]

[pos]
embedded = false
